version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - "3308:5432"  # Map host port 3308 to container port 5432
    environment:
      POSTGRES_DB: employeedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lucknow11kanto@